name: SQL Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run SQL validation tests
        run: |
          pytest -v