name: Run SQL Data Quality Checks

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual run

jobs:
  sql-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run SQL Data Quality Checks
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DB: ${{ secrets.SQL_DB }}
        run: |
          echo "Running Data Quality Checks..."
          sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DB -i sql/data_quality_checks.sql > results.txt

          echo "Results from data checks:"
          cat results.txt

          if grep -E "MissingCustomerID|InvalidAmounts|NullFields" results.txt | grep -v "0"; then
            echo "❌ Data Quality Checks Failed!"
            exit 1
          else
            echo "✅ All Data Quality Checks Passed!"
          fi
